export const ACCOUNTS_LIST = 'ACCOUNTS_LIST'
export const ACCOUNT_TYPE = 'ACCOUNT_TYPE'
export const ACCOUNTS = 'ACCOUNTS'

export const LEVERAGE = 'LEVERAGE'
export const ACCOUNT = 'ACCOUNT'
export const BALANCE = 'BALANCE'
export const EQUITY = 'EQUITY'
export const CREDIT = 'CREDIT'

export const INVESTORS_ACCOUNT_LIST = 'INVESTORS_ACCOUNT_LIST'
export const PROFIT = 'PROFIT'
export const USER_NAME = 'USER_NAME'
export const ACCOUNT_AVATAR = 'ACCOUNT_AVATAR'

export const DEMO_ACCOUNT_LIST = 'DEMO_ACCOUNT_LIST'
export const ARCHIVE_ACCOUNT_LIST = 'ARCHIVE_ACCOUNT_LIST'

export const TRADING_TERMINALS = 'TRADING_TERMINALS'
export const TITLE = 'TITLE'
export const ACCOUNT_INFO = 'ACCOUNT_INFO'

export const LOAD_ACCOUNT_INFO = 'LOAD_ACCOUNT_INFO'

export const GET_ACCOUNT_GENERAL_INFORMATION = 'GET_ACCOUNT_GENERAL_INFORMATION'
export const GET_ACCOUNT_FINANCE_INFORMATION = 'GET_ACCOUNT_FINANCE_INFORMATION'

export const AVAILABLE_STATISTICS_PERIODS = 'AVAILABLE_STATISTICS_PERIODS'
export const GET_AVAILABLE_STATISTICS_PERIODS = 'GET_AVAILABLE_STATISTICS_PERIODS'
export const SELECTED_STATISTICS_PERIOD = 'SELECTED_STATISTICS_PERIOD'
export const GET_SELECTED_STATISTICS_PERIOD = 'GET_SELECTED_STATISTICS_PERIOD'
export const CHANGE_SELECTED_STATISTICS_PERIOD = 'CHANGE_SELECTED_STATISTICS_PERIOD'

export const CURRENT_ORDERS_LIST = 'CURRENT_ORDERS_LIST'
export const ORDER_HISTORY_LIST = 'ORDER_HISTORY_LIST'
export const ORDER_ITEM = 'ORDER_ITEM'
export const GET_ORDER_ITEM = 'GET_ORDER_ITEM'
export const ORDER_FILTERING = 'ORDER_FILTERING'
export const ORDER_PERIOD_FILTERING = 'ORDER_PERIOD_FILTERING'
export const CLOSED_ORDERS = 'CLOSED_ORDERS'
export const DEPOSITS = 'DEPOSITS'
export const WITHDRAWALS = 'WITHDRAWALS'
export const REBATES = 'REBATES'
export const INTERNAL_TRANSFER = 'INTERNAL_TRANSFER'
export const SWAP = 'SWAP'
export const FEES_COMMISSIONS = 'FEES_COMMISSIONS'
export const GET_ORDER_FILTERING = 'GET_ORDER_FILTERING'
export const UPDATE_ORDER_TYPE_FILTER = 'UPDATE_ORDER_TYPE_FILTER'
export const FILTER_LABELS = 'FILTER_LABELS'
export const GET_FILTER_LABELS = 'GET_FILTER_LABELS'

export const TODAY = 'TODAY'
export const YESTERDAY = 'YESTERDAY'
export const LAST_7_DAYS = 'LAST_7_DAYS'
export const LAST_30_DAYS = 'LAST_30_DAYS'
export const THIS_MONTH = 'THIS_MONTH'
export const PREVIOUS_MONTH = 'PREVIOUS_MONTH'
export const CUSTOM_PERIOD = 'CUSTOM_PERIOD'

export const UPDATE_ORDER_PERIOD_FILTER = 'UPDATE_ORDER_PERIOD_FILTER'
export const GET_ORDER_PERIOD_FILTERING = 'GET_ORDER_PERIOD_FILTERING'

export const SELECTED_PERIOD_FILTER = 'SELECTED_PERIOD_FILTER'

export const CUSTOM_PERIOD_RANGE = 'CUSTOM_PERIOD_RANGE'
export const START = 'START'
export const END = 'END'
export const UPDATE_CUSTOM_FILTER_PERIOD = 'UPDATE_CUSTOM_FILTER_PERIOD'

export const GET_CUSTOM_PERIOD_RANGE = 'GET_CUSTOM_PERIOD_RANGE'
export const GET_SELECTED_PERIOD_FILTER = 'GET_SELECTED_PERIOD_FILTER'

export const GET_ACCOUNT_NAME = 'GET_ACCOUNT_NAME'
export const GET_ACCOUNT_SOCIAL_TRADING_INFORMATION = 'GET_ACCOUNT_SOCIAL_TRADING_INFORMATION'

export const COPYING_SESSION = 'COPYING_SESSION'
export const GET_COPYING_SESSION = 'GET_COPYING_SESSION'

export const DEMO_ACCOUNT_LIST_LOADING_STATE = 'DEMO_ACCOUNT_LIST_LOADING_STATE'

export const REAL_ACCOUNT_LIST_LOADING_STATE = 'REAL_ACCOUNT_LIST_LOADING_STATE'

export const ACCOUNT_INFO_IN_PROGRESS = 'ACCOUNT_INFO_IN_PROGRESS'

export const OPEN_ACCOUNT_TYPE = 'OPEN_ACCOUNT_TYPE'
export const SELECTED_OPEN_ACCOUNT_TYPE = 'SELECTED_OPEN_ACCOUNT_TYPE'
export const LEVERAGE_TYPE = 'LEVERAGE_TYPE'
export const SELECTED_LEVERAGE_TYPE = 'SELECTED_LEVERAGE_TYPE'
export const CURRENCY_ACCOUNT = 'CURRENCY_ACCOUNT'
export const SELECTED_CURRENCY_ACCOUNT = 'SELECTED_CURRENCY_ACCOUNT'
