export const GET_DEMO_ACCOUNT_LIST = 'GET_DEMO_ACCOUNT_LIST'

export const GET_ACCOUNT_INFO_IN_PROGRESS = 'GET_ACCOUNT_INFO_IN_PROGRESS'

export const GET_IS_SWAP_FREE = 'GET_IS_SWAP_FREE'

export const GET_GENERAL_IS_IN_PROGRESS = 'GET_GENERAL_IS_IN_PROGRESS'

export const GET_ACCOUNTS_LIST = 'GET_ACCOUNTS_LIST'

export const GET_OPEN_ACCOUNT_TYPE = 'GET_OPEN_ACCOUNT_TYPE'

export const GET_SELECTED_OPEN_ACCOUNT_TYPE = 'GET_SELECTED_OPEN_ACCOUNT_TYPE'

export const GET_LEVERAGE_TYPE = 'GET_LEVERAGE_TYPE'

export const GET_SELECTED_LEVERAGE_TYPE = 'GET_SELECTED_LEVERAGE_TYPE'

export const GET_CURRENCY_ACCOUNT = 'GET_CURRENCY_ACCOUNT'

export const GET_SELECTED_CURRENCY_ACCOUNT = 'GET_SELECTED_CURRENCY_ACCOUNT'
