export const SET_DEMO_ACCOUNT_LIST = 'SET_DEMO_ACCOUNT_LIST'
export const SET_DEMO_ACCOUNT_LIST_IN_PROGRESS = 'SET_DEMO_ACCOUNT_LIST_IN_PROGRESS'

export const SET_REAL_ACCOUNT_LIST = 'SET_REAL_ACCOUNT_LIST'
export const SET_REAL_ACCOUNT_LIST_IN_PROGRESS = 'SET_REAL_ACCOUNT_LIST_IN_PROGRESS'

export const SET_ACCOUNT_INFO_IN_PROGRESS = 'SET_ACCOUNT_INFO_IN_PROGRESS'

export const CHANGE_SELECTED_OPEN_ACCOUNT_TYPE = 'CHANGE_SELECTED_OPEN_ACCOUNT_TYPE'
export const CHANGE_SELECTED_LEVERAGE_TYPE = 'CHANGE_SELECTED_LEVERAGE_TYPE'
export const CHANGE_CURRENCY_ACCOUNT = 'CHANGE_CURRENCY_ACCOUNT'
