/**
 * state
 */
export const RATING_LIST = 'RATING_LIST'
export const DAYS = 'DAYS'
export const AVATAR = 'AVATAR'
export const USER_NAME = 'USER_NAME'
export const ACCOUNT_NAME = 'ACCOUNT_NAME'
export const AVERAGE_MONTH_PROFITABILITY = 'AVERAGE_MONTHLY_PROFITABILITY'
export const EQUITY = 'EQUITY'
export const INVESTORS = 'INVESTORS'
export const INVESTORS_EQUITY = 'INVESTORS_EQUITY'
export const SELECTED_PERIOD = 'SELECTED_PERIOD'
export const PERIOD_LABELS = 'PERIOD_LABELS'

export const OVERALL = 'OVERALL'
export const ONE_YEAR = 'ONE_YEAR'
export const SIX_MONTH = 'SIX_MONTH'
export const THREE_MONTH = 'THREE_MONTH'
export const ONE_MONTH = 'ONE_MONTH'
export const ONE_WEEK = 'ONE_WEEK'

export const FILTER_SETTINGS = 'FILTER_SETTINGS'
export const PROFITABILITY = 'PROFITABILITY'
export const TRADERS_COMMISSION = 'TRADERS_COMMISSION'
export const LIFESPAN = 'LIFESPAN'

export const TRADER_ACCOUNTS = 'TRADER_ACCOUNTS'
export const SELECTED_PROVIDER_SUB_PAGE = 'SELECTED_PROVIDER_SUB_PAGE'

export const TRADER_SUMMARY_INFO = 'TRADER_SUMMARY_INFO'

/**
 * getters
 */
export const GET_RATING_LIST = 'GET_RATING_LIST'
export const GET_SELECTED_PERIOD = 'GET_SELECTED_PERIOD'
export const GET_SELECTED_PERIOD_LABEL = 'GET_SELECTED_PERIOD_LABEL'
export const GET_PROFITABILITY_FILTER = 'GET_PROFITABILITY_FILTER'
export const GET_EQUITY_FILTER = 'GET_EQUITY_FILTER'
export const GET_LIFESPAN_FILTER = 'GET_LIFESPAN_FILTER'
export const GET_INVESTOR_FILTER = 'GET_INVESTOR_FILTER'
export const GET_INVESTORS_EQUITY_FILTER = 'GET_INVESTORS_EQUITY_FILTER'
export const GET_TRADERS_COMMISSION_FILTER = 'GET_TRADERS_COMMISSION_FILTER'

export const GET_TRADER_ACCOUNTS_NAMES = 'GET_TRADER_ACCOUNTS_NAMES'

export const GET_SELECTED_PROVIDER_SUB_PAGE = 'GET_SELECTED_PROVIDER_SUB_PAGE'

export const GET_TRADER_SUMMARY_INFO = 'GET_TRADER_SUMMARY_INFO'

export const GET_SELECTED_TRADER_ACCOUNT_INFO = 'GET_SELECTED_TRADER_ACCOUNT_INFO'

/**
 * mutations
 */
export const SET_SELECTED_PERIOD = 'SET_SELECTED_PERIOD'
export const SET_PROFITABILITY_FILTER = 'SET_PROFITABILITY_FILTER'
export const SET_EQUITY_FILTER = 'SET_EQUITY_FILTER'
export const SET_TRADERS_COMMISSION_FILTER = 'SET_TRADERS_COMMISSION_FILTER'
export const SET_LIFESPAN_FILTER = 'SET_LIFESPAN_FILTER'
export const SET_INVESTORS_FILTER = 'SET_INVESTORS_FILTER'
export const SET_INVESTORS_EQUITY_FILTER = 'SET_INVESTORS_EQUITY_FILTER'
export const SET_SELECTED_PROVIDER_SUB_PAGE = 'SET_SELECTED_PROVIDER_SUB_PAGE'
