export const CHANGE_SUMMARY_STATISTICS = 'CHANGE_SUMMARY_STATISTICS'
export const CHANGE_ACCOUNT_SOCIAL_TRADER = 'CHANGE_ACCOUNT_SOCIAL_TRADER'
export const CHANGE_NICKNAME_INVESTOR = 'CHANGE_NICKNAME_INVESTOR'
