export const GET_PROMOTIONS_INFO = 'GET_PROMOTIONS_INFO'
export const GET_PROMOTIONS_INFO_BLOCKS = 'GET_PROMOTIONS_INFO_BLOCKS'
export const GET_MY_PROMOTIONS_INFO_BLOCKS = 'GET_MY_PROMOTIONS_INFO_BLOCKS'
