export const LIST = 'LIST'
export const IN_PROGRESS = 'IN_PROGRESS'
export const CAN_VIEW_LOAD_MORE_BUTTON = 'CAN_VIEW_LOAD_MORE_BUTTON'
export const CURRENT_PAGE = 'CURRENT_PAGE'
export const ERRORS = 'ERRORS'
